// Copyright Bryan Carroll. All rights reserved.
//
//  SplashScreen.swift
//  Trek Long Island
//
//  Regenerated by ChatGPT on 8/15/25
//

import SwiftUI

struct SplashScreen: View {
    // Theme & accessibility
    @Environment(\.colorScheme) private var scheme
    @Environment(\.accessibilityReduceMotion) private var reduceMotion

    // Simple logo animation
    @State private var logoOpacity: Double = 0.0
    @State private var logoScale: CGFloat = 0.92

    // Display text (override if needed)
    var title: String = ""
    var subtitle: String = ""

    var body: some View {
        ZStack {
            // Background: prefer image if available, else app gradient
            if imageExists("planetBackground") {
                Image("planetBackground")
                    .resizable()
                    .scaledToFill()
                    .ignoresSafeArea()
            } else {
                TLITheme.backgroundGradient(scheme)
                    .ignoresSafeArea()
            }

            // Subtle readability veil from bottom
            LinearGradient(
                colors: [.black.opacity(0.35), .clear],
                startPoint: .bottom, endPoint: .center
            )
            .ignoresSafeArea()
            .allowsHitTesting(false)

            // Content
            VStack(spacing: 16) {
                // Logo / mark
                Group {
                    if imageExists("Splash5") {
                        Image("Splash5")
                            .resizable()
                            .scaledToFit()
                            .frame(maxWidth: 320, maxHeight: 320)
                            .scaleEffect(logoScale)
                            .opacity(logoOpacity)
                            .shadow(color: .black.opacity(0.25), radius: 10, y: 4)
                            .accessibilityHidden(true)
                    } else {
                        // Fallback symbol if no asset
                        Image(systemName: "sparkles")
                            .font(.system(size: 120, weight: .thin))
                            .opacity(logoOpacity)
                            .scaleEffect(logoScale)
                            .foregroundStyle(TLITheme.textPrimary(scheme))
                            .shadow(radius: 4)
                            .accessibilityHidden(true)
                    }
                }

                // Titles
                Text(title)
                    .font(.largeTitle.bold())
                    .multilineTextAlignment(.center)
                    .foregroundStyle(TLITheme.textPrimary(scheme))
                    .shadow(radius: 2)

                Text(subtitle)
                    .font(.headline)
                    .multilineTextAlignment(.center)
                    .foregroundStyle(TLITheme.textSecondary(scheme))
            }
            // Keep content toward the lower third for nicer composition
            .padding(.horizontal, 24)
            .padding(.bottom, 60)
            .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .bottom)
        }
        .onAppear(perform: runIntroAnimation)
        // Let parent (TrekLIApp) handle tap-to-skip;
        // make sure nothing inside blocks taps.
        .contentShape(Rectangle())
    }

    // MARK: - Animation
    private func runIntroAnimation() {
        if reduceMotion {
            logoOpacity = 1.0
            logoScale = 1.0
            return
        }
        withAnimation(.easeOut(duration: 0.7)) {
            logoOpacity = 1.0
            logoScale = 1.0
        }
        // Optional gentle breathing after fade-in
        withAnimation(.easeInOut(duration: 1.6).repeatForever(autoreverses: true)) {
            logoScale = 1.02
        }
    }

    // MARK: - Helpers
    private func imageExists(_ name: String) -> Bool {
        UIImage(named: name) != nil
    }
}

#Preview {
    Group {
        SplashScreen()
            .environment(\.colorScheme, .light)

        SplashScreen()
            .environment(\.colorScheme, .dark)
    }
}
